# Generated by Django 5.1.7 on 2025-04-09 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 0, 58, 17, 847900, tzinfo=datetime.timezone.utc)),
        ),
    ]
