# Generated by Django 5.1.7 on 2025-03-25 10:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0002_remove_borrower_borrowed_books_remove_borrower_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True, default=2002),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.book'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 10, 44, 9, 74427, tzinfo=datetime.timezone.utc)),
        ),
    ]
