# Generated by Django 5.1.7 on 2025-04-09 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0002_alter_borrowedbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 1, 27, 30, 478020, tzinfo=datetime.timezone.utc)),
        ),
    ]
