# Generated by Django 5.1.7 on 2025-03-25 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0003_borrowedbook_borrow_date_alter_borrowedbook_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 10, 56, 29, 39041, tzinfo=datetime.timezone.utc)),
        ),
    ]
