# Generated by Django 5.1.7 on 2025-04-10 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0003_alter_borrowedbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 13, 0, 54, 33, 663469, tzinfo=datetime.timezone.utc)),
        ),
    ]
