# Generated by Django 5.1.7 on 2025-04-10 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0004_alter_borrowedbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 13, 1, 37, 39, 65568, tzinfo=datetime.timezone.utc)),
        ),
    ]
