# Generated by Django 5.1.7 on 2025-03-25 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0006_alter_borrowedbook_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrow_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
