# Generated by Django 5.1.7 on 2025-03-25 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0007_remove_borrowedbook_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 11, 41, 52, 6765, tzinfo=datetime.timezone.utc)),
        ),
    ]
