# Generated by Django 5.1.7 on 2025-04-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0007_alter_adminprofile_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Returned', 'Returned')], default='Borrowed', max_length=10),
        ),
    ]
