# Generated by Django 5.1.7 on 2025-03-27 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0009_alter_borrowedbook_due_date_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 23, 55, 51, 588970, tzinfo=datetime.timezone.utc)),
        ),
    ]
