# Generated by Django 5.1.7 on 2025-03-28 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0010_alter_borrowedbook_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 9, 24, 23, 985910, tzinfo=datetime.timezone.utc)),
        ),
    ]
