# Generated by Django 5.1.7 on 2025-03-28 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0011_alter_borrowedbook_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 9, 37, 52, 878042, tzinfo=datetime.timezone.utc)),
        ),
    ]
